name: flutter_blue_plus_windows
description: Flutter blue plus for Windows
version: 1.26.1
repository: https://github.com/chan150/flutter_blue_plus_windows
#publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # https://pub.dev/packages/flutter_blue_plus
  flutter_blue_plus: ^1.36.8
  # https://pub.dev/packages/flutter_blue_plus_platform_interface
  flutter_blue_plus_platform_interface: 7.0.0
  # https://pub.dev/packages/win_ble
  win_ble: ">=1.1.1"
  # https://pub.dev/packages/stream_with_value
  stream_with_value: ">=0.5.0"
